services:
  development:
    image: samminhch/testing:development
    build:
      context: .
      dockerfile: Docker/Dockerfile
      target: development
    tty: True
    stdin_open: True
    volumes:
      - ./.config:/root/.config
