name: Docker Image Build and Push

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'Docker/Dockerfile'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Docker/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker login --username samminhch --password ${{ secrets.DOCKERHUB_PASSWORD }}
        docker compose build --push
